version: "3.7"
services: 
    congressoemchamas:
        image: pimentgabriel/congressoemchamas
        environment: 
            - PORT=80
            - GOOGLE_NEWS_API_KEY=d97966c338b44bffbeb4957480bd0d74
            - JDBC_DATABASE_URL=jdbc:postgresql://postgres/postgres?user=postgres&password=${POSTGRES_PASSWORD}
            - TWITTER_ACCESS_TOKEN=42526425-BCMdBupTQ2E2RP6L8aKTsc2uP6FyPLMAubn9mznJv
            - TWITTER_ACCESS_TOKEN_SECRET=VFZaLSeDXSAgOLoWih8NBdHGiX5BDRVgaUMPs4HKouNxT
            - TWITTER_CONSUMER_KEY=mZPuiaSORinju4bY2QBQUhNJC
            - TWITTER_CONSUMER_SECRET=tYyofsR3zIWAirCKYc8CzZlwFCoHhmF5CFWH8T5s1dTH01IGId
        ports:
            - "80:80"
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - congresso-db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=congressoemchamas
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports: 
            - "5050:80"

volumes: 
    congresso-db:

# Log in pgadmin using localhost:5050, and create postgres server with:
# host: postgres
# port: 5432
# username: postgres
# password: password