version: "3.7"
services: 
    congressoemchamas:
        image: pimentgabriel/congressoemchamas
        environment: 
            - PORT=80
            - CAMARA_API_URL=dadosabertos.camara.leg.br/api/v2
            - GOOGLE_NEWS_API_KEY=d97966c338b44bffbeb4957480bd0d74
            - GOOGLE_NEWS_API_URL=newsapi.org/v2/everything
            - JDBC_DATABASE_USERNAME=postgres
            - JDBC_DATABASE_PASSWORD=password
            - JDBC_DATABASE_URL=jdbc:postgresql://postgres/postgres?user=postgres&password=password
            - TWITTER_ACCESS_TOKEN=42526425-BCMdBupTQ2E2RP6L8aKTsc2uP6FyPLMAubn9mznJv
            - TWITTER_ACCESS_TOKEN_SECRET=VFZaLSeDXSAgOLoWih8NBdHGiX5BDRVgaUMPs4HKouNxT
            - TWITTER_CONSUMER_KEY=mZPuiaSORinju4bY2QBQUhNJC
            - TWITTER_CONSUMER_SECRET=tYyofsR3zIWAirCKYc8CzZlwFCoHhmF5CFWH8T5s1dTH01IGId
        ports:
            - "80:80"
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=username
            - PGADMIN_DEFAULT_PASSWORD=password

# Log in pgadmin using localhost:5050, and create postgres server with:
# host: postgres
# port: 5432
# username: postgres
# password: password